#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/halo

PRODUCT_COPY_FILES += \
    vendor/lenovo/halo/proprietary/product/etc/permissions/UimGba.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimGba.xml \
    vendor/lenovo/halo/proprietary/product/etc/permissions/UimGbaManager.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimGbaManager.xml \
    vendor/lenovo/halo/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/lenovo/halo/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/IDP_UPD/IDP_UPD_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP_UPD/IDP_UPD_workspaceFileXml.qwsp \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.4_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.4_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.4_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.4_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.1_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.1_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/waipio_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_mtp/MTP_acdb_cal.acdb \
    vendor/lenovo/halo/proprietary/vendor/etc/acdbdata/waipio_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_mtp/MTP_workspaceFileXml.qwsp \
    vendor/lenovo/halo/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/audio/sku_cape/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/audio_effects.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/audio/sku_cape/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/audio_effects.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/audio/sku_cape/resourcemanager_upd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_upd.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/3840black.UBWCTP10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/3840black.UBWCTP10 \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/black.UBWCTP10:$(TARGET_COPY_OUT_VENDOR)/etc/camera/black.UBWCTP10 \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/cal_w48_u16_default.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cal_w48_u16_default.bin \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eisoverridesettings.txt \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/bst_cfg/control_param_DSLR_test_encode.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/bst_cfg/control_param_DSLR_test_encode.txt \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/bst_cfg/control_param_pfremove_Test_Lenovo_enc.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/bst_cfg/control_param_pfremove_Test_Lenovo_enc.cfg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/globalwhitelist.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/globalwhitelist.txt \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/golden_calibration/cameracalibration.rc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/golden_calibration/cameracalibration.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/golden_calibration/golden.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/golden_calibration/golden.bin \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/WLXY.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/WLXY.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/chuandao.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/chuandao.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/contrast.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/contrast.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/fengyu.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/fengyu.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/filmStyle.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/filmStyle.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/moon.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/moon.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/orange.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/orange.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/pailide.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/pailide.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/shengxia.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/shengxia.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/sunnyDay.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/sunnyDay.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/tf3.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/tf3.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/vig.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/vig.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/lutfiles/yecan.mslut:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/lutfiles/yecan.mslut \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/FA59C257-6E6C-4C4A-B24E-67DF37FA2470.1.warp:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/FA59C257-6E6C-4C4A-B24E-67DF37FA2470.1.warp \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/FA59C257-6E6C-4C4A-B24E-67DF37FA2470.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/FA59C257-6E6C-4C4A-B24E-67DF37FA2470.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/meishe.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/meishe.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/mode/ms_face240_v1.0.3.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/mode/ms_face240_v1.0.3.model \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/mode/ms_face_v1.2.2.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/mode/ms_face_v1.2.2.model \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/mode/ms_faceattr_faceshape_v1.0.0.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/mode/ms_faceattr_faceshape_v1.0.0.model \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/mode/ms_faceattr_v1.0.0.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/mode/ms_faceattr_v1.0.0.model \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/meisheEffect/mode/pe240_ms_v1.0.0.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/meisheEffect/mode/pe240_ms_v1.0.0.dat \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/morpho_xml/morpho_hdsr_tuning_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/morpho_xml/morpho_hdsr_tuning_params.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/morpho_xml/morpho_image_refiner_hdr_tuning_params_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/morpho_xml/morpho_image_refiner_hdr_tuning_params_0.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.360ai.PortraitMask.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.360ai.PortraitMask.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.arcsoft.superportrait.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.arcsoft.superportrait.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.bst.purplefringeremove.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.bst.purplefringeremove.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.Watermark.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.Watermark.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.bokeh.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.bokeh.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.pip.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.lenovo.pip.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.meishe.beauty.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.meishe.beauty.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.meishe.effect.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.meishe.effect.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.morpho.denoise.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.morpho.denoise.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.morpho.hdrdetector.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.morpho.hdrdetector.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.morpho.imageRefiner.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.morpho.imageRefiner.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.morpho.singlebokeh.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.morpho.singlebokeh.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.algorithm.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.algorithm.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.conditions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.conditions.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.conditions.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.conditions.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.pipeline.PreviewVideo.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.pipeline.PreviewVideo.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.pipeline.Snapshot.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.pipeline.Snapshot.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.pipeline.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.pipeline.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_front/Pandora.segment.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_front/Pandora.segment.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.hdrchecker.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.hdrchecker.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.lowlighthdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.lowlighthdr.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.normalhdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.arcsoft.normalhdr.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.bst.aicapture.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.bst.aicapture.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.lenovo.Watermark.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.lenovo.Watermark.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.lenovo.pip.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.lenovo.pip.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.meishe.effect.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.meishe.effect.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.morpho.denoise.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.morpho.denoise.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.morpho.motionsensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.morpho.motionsensor.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.morpho.sr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.morpho.sr.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.algorithm.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.algorithm.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.conditions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.conditions.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.conditions.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.conditions.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.pipeline.PreviewVideo.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.pipeline.PreviewVideo.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.pipeline.Snapshot.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.pipeline.Snapshot.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.pipeline.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.pipeline.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_main/Pandora.segment.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_main/Pandora.segment.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.hdrchecker.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.hdrchecker.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.lowlighthdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.lowlighthdr.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.normalhdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.arcsoft.normalhdr.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.lenovo.Watermark.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.lenovo.Watermark.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.meishe.effect.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.meishe.effect.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.dc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.dc.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.dccapture.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.dccapture.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.denoise.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.morpho.denoise.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.niklas.DummyPreviewVideoAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.niklas.DummySnapshotAlgorithm.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.algorithm.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.algorithm.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.conditions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.conditions.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.conditions.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.conditions.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.pipeline.PreviewVideo.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.pipeline.PreviewVideo.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.pipeline.Snapshot.1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.pipeline.Snapshot.1.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.pipeline.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.pipeline.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/source_wide/Pandora.segment.xsd:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/source_wide/Pandora.segment.xsd \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/0FD9D336-07C2-4CAA-BCE2-85F01367AF03.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/0FD9D336-07C2-4CAA-BCE2-85F01367AF03.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/0FD9D336-07C2-4CAA-BCE2-85F01367AF03.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/0FD9D336-07C2-4CAA-BCE2-85F01367AF03.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/1292A462-EAE3-4FA2-AFAD-2DB3A4B947B5.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/1292A462-EAE3-4FA2-AFAD-2DB3A4B947B5.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/1292A462-EAE3-4FA2-AFAD-2DB3A4B947B5.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/1292A462-EAE3-4FA2-AFAD-2DB3A4B947B5.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/21ED4E09-E19A-4D3E-B8B6-CC4ED8E4A513.2.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/21ED4E09-E19A-4D3E-B8B6-CC4ED8E4A513.2.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/21ED4E09-E19A-4D3E-B8B6-CC4ED8E4A513.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/21ED4E09-E19A-4D3E-B8B6-CC4ED8E4A513.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/2EAC219C-E7F0-42F5-9839-E17E42AE390F.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/2EAC219C-E7F0-42F5-9839-E17E42AE390F.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/2EAC219C-E7F0-42F5-9839-E17E42AE390F.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/2EAC219C-E7F0-42F5-9839-E17E42AE390F.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/3A0DB289-238C-4FE4-8FD4-90B6ACFFBCCD.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/3A0DB289-238C-4FE4-8FD4-90B6ACFFBCCD.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/3A0DB289-238C-4FE4-8FD4-90B6ACFFBCCD.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/3A0DB289-238C-4FE4-8FD4-90B6ACFFBCCD.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/3C1C1944-117F-4D4C-8432-22D165CB27BC.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/3C1C1944-117F-4D4C-8432-22D165CB27BC.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/3C1C1944-117F-4D4C-8432-22D165CB27BC.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/3C1C1944-117F-4D4C-8432-22D165CB27BC.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/530A825F-0E62-4459-9767-6B41BB97FE52.4.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/530A825F-0E62-4459-9767-6B41BB97FE52.4.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/530A825F-0E62-4459-9767-6B41BB97FE52.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/530A825F-0E62-4459-9767-6B41BB97FE52.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/61B3A8B9-C843-450D-AB93-56FF082FF120.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/61B3A8B9-C843-450D-AB93-56FF082FF120.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/61B3A8B9-C843-450D-AB93-56FF082FF120.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/61B3A8B9-C843-450D-AB93-56FF082FF120.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/A51583C8-8424-467C-B73E-54A3CBF213F7.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/A51583C8-8424-467C-B73E-54A3CBF213F7.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/A51583C8-8424-467C-B73E-54A3CBF213F7.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/A51583C8-8424-467C-B73E-54A3CBF213F7.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/BA31F006-295F-4247-AE69-73F9E56F5DA9.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/BA31F006-295F-4247-AE69-73F9E56F5DA9.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/BA31F006-295F-4247-AE69-73F9E56F5DA9.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/BA31F006-295F-4247-AE69-73F9E56F5DA9.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/FC609EA5-C385-49D1-8576-53EAEE4A01C1.1.videofx:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/FC609EA5-C385-49D1-8576-53EAEE4A01C1.1.videofx \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/pandora/videofx/FC609EA5-C385-49D1-8576-53EAEE4A01C1.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pandora/videofx/FC609EA5-C385-49D1-8576-53EAEE4A01C1.lic \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/10_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/10_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/10_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/10_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/1_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/1_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/1_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/1_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/2_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/2_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/2_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/2_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/3_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/3_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/3_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/3_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/4_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/4_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/4_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/4_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/5_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/5_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/5_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/5_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/6_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/6_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/6_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/6_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/7_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/7_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/7_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/7_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/8_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/8_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/8_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/8_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/9_0.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/9_0.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/9_90.jpg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/9_90.jpg \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/AW_Portrait_Mask_License.data:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/AW_Portrait_Mask_License.data \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/PS_F_N_v3_E.m.awcache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/PS_F_N_v3_E.m.awcache \
    vendor/lenovo/halo/proprietary/vendor/etc/camera/portrait/PS_F_N_v3_E.m.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portrait/PS_F_N_v3_E.m.bin \
    vendor/lenovo/halo/proprietary/vendor/etc/display/qdcm_calib_data_NOVA_NT37701A_cmd_mode_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_NOVA_NT37701A_cmd_mode_panel_with_DSC.json \
    vendor/lenovo/halo/proprietary/vendor/etc/display/qdcm_merge_rules_NOVA_NT37701A_cmd_mode_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_merge_rules_NOVA_NT37701A_cmd_mode_panel_with_DSC.json \
    vendor/lenovo/halo/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/dolby_vision.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/dolby_vision.cfg \
    vendor/lenovo/halo/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/android.hardware.gnss-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-aidl-service-qti.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/hw/init.lenovo.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.lenovo.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/init.embmssl_server.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.embmssl_server.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/qcrilNrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrilNrd.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.dolby.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2@1.0-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.dolby.media.dvs-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.dvs-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.dolby.vision.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.vision.media.c2@1.0-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.lenovo.hardware.ifaa@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lenovo.hardware.ifaa@1.0-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.nxp.hardware.nfc@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.nxp.hardware.nfc@2.0-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.qti.camera.provider@2.7-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.camera.provider@2.7-service_64.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/init/vendor.qti.secure_element@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.secure_element@1.2-service.rc \
    vendor/lenovo/halo/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-SN220.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-SN220.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-mtp-SN100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-SN100.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-mtp-SN100_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-SN100_38_4MHZ.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-qrd-SN100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-SN100.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/libnfc-qrd-SN100_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-SN100_38_4MHZ.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/qcrilNr.db:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/qcrilNr.db \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/10.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/10.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/11.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/11.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/12.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/12.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/13.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/13.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/6.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/6.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/7.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/7.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/8.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/8.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/config/9.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/9.0_config.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/0_initial_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/0_initial_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/10_version_update_ecc_table.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/11_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/11_version_update_ecc_table.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/12_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/12_version_update_ecc_table.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/1_version_intro_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/1_version_intro_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/4_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/4_version_update_ecc_table_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/5_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/5_version_update_ecc_table_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/7_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/7_version_update_ecc_table_qcrilnr.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/8_version_update_ecc_table.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/qcril_database/upgrade/other/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/9_version_update_ecc_table.sql \
    vendor/lenovo/halo/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_CPU_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_CPU_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_CPU_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_CPU_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_CPU_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_CPU_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_DDR_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_DDR_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_DDR_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_DDR_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_DDR_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_DDR_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_LLCC_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_LLCC_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_LLCC_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_LLCC_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/scheduler_config_LLCC_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scheduler_config_LLCC_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-inet-agent.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-inet-agent.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/seccomp_policy/qcrilnr@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qcrilnr@2.0.policy \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/mot_chopchop_halo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_chopchop_halo.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/qsh_camera.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_default_sensors.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_dynamic_sensors.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_halo_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_halo_mmc56x3x_0.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_icm4x6xx_0.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_irq.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_power_0.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/config/waipio_stk3a5x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_stk3a5x_0.json \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_battery_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_battery_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_battery_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_common_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_common_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_common_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_common_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_3.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_4.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_5.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_5.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_6.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_6.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_7.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_7.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_8.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_8.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_cpu_9.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_9.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_fan_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_fan_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_gpu_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_gpu_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_gpu_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_2.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_gpu_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_3.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_gpu_4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_4.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_sensor_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_sensor_0.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal-engine_sensor_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_sensor_1.conf \
    vendor/lenovo/halo/proprietary/vendor/etc/thermal_user_case.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_user_case.conf \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/lenovo/halo/proprietary/vendor/firmware/CAMERA_ICP_480.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_480.elf \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_0.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_1.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_2.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_3.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_4.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_5.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_6.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_7.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_8.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_cfg_9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_cfg_9.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_fw.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_0.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_1.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_2.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_3.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_4.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw22127_lamp2_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22127_lamp2_5.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw8680x_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8680x_flash.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw8680x_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8680x_sram.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/100_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/100_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/101_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/101_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/102_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/102_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/103_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/103_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/104_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/104_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/105_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/105_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/106_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/106_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/107_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/107_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/108_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/108_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/109_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/109_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/110_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/110_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/111_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/111_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/112_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/112_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/113_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/113_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/114_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/114_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/115_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/115_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/116_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/116_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/117_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/117_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/118_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/118_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/119_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/119_Haptic_Right_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/144_LightWaves_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/144_LightWaves_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/145_Time_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/145_Time_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/146_Starlight_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/146_Starlight_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/147_Interstellar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/147_Interstellar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/148_LightItUp_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/148_LightItUp_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/149_Twinkling_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/149_Twinkling_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/150_Disappear_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/150_Disappear_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/151_AGT_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/151_AGT_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/152_Aircraft_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/152_Aircraft_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/153_BaBa_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/153_BaBa_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/154_Bloom_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/154_Bloom_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/155_Bottle_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/155_Bottle_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/156_Bright_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/156_Bright_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/157_CountryGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/157_CountryGuitar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/158_Di_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/158_Di_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/159_Drip_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/159_Drip_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/160_Du_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/160_Du_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/161_Dudu_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/161_Dudu_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/162_FleetingTime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/162_FleetingTime_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/163_Flowering_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/163_Flowering_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/164_Fluting_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/164_Fluting_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/165_FoodBell_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/165_FoodBell_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/166_GoGo_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/166_GoGo_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/167_Mechanical_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/167_Mechanical_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/168_Mouse_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/168_Mouse_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/169_Laser_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/169_Laser_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/170_Ring_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/170_Ring_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/171_Win_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/171_Win_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/172_Signal_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/172_Signal_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/173_Sword_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/173_Sword_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/174_Sports_Car_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/174_Sports_Car_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/175_Race_Car_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/175_Race_Car_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/176_Stable_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/176_Stable_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/177_Strange_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/177_Strange_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/178_Stream_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/178_Stream_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/179_Success_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/179_Success_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/180_Talk_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/180_Talk_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/181_Technology_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/181_Technology_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/182_Telly_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/182_Telly_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/183_tone_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/183_tone_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/184_Tumbler_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/184_Tumbler_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/185_Footsteps_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/185_Footsteps_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/186_Wave_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/186_Wave_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/187_Blinking_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/187_Blinking_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/188_Brisk_moment_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/188_Brisk_moment_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/189_ClassicPiano_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/189_ClassicPiano_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/190_Clear_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/190_Clear_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/191_DalaGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/191_DalaGuitar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/192_DingDang_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/192_DingDang_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/193_DoDaDa_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/193_DoDaDa_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/194_Dreamtime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/194_Dreamtime_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/195_Early_morninng_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/195_Early_morninng_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/196_Eighties_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/196_Eighties_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/197_FunkyGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/197_FunkyGuitar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/198_Guitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/198_Guitar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/199_HappyTime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/199_HappyTime_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/200_Home_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/200_Home_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/201_Jete_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/201_Jete_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/202_Kalimba_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/202_Kalimba_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/203_landscape_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/203_landscape_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/204_LullabyPiano_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/204_LullabyPiano_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/205_MaLing_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/205_MaLing_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/206_Moment_of_spirit_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/206_Moment_of_spirit_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/207_PianoNoise_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/207_PianoNoise_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/208_PingPong_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/208_PingPong_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/209_RainbowSweet_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/209_RainbowSweet_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/210_Travel_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/210_Travel_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/211_Soothing_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/211_Soothing_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/212_Elves_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/212_Elves_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/213_Psychedelic_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/213_Psychedelic_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/214_Dark_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/214_Dark_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/215_Promote_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/215_Promote_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/216_Lenovo_Electronic_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/216_Lenovo_Electronic_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/217_Lenovo_Gaming_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/217_Lenovo_Gaming_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/218_Lenovo_Guitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/218_Lenovo_Guitar_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/219_Lenovo_Dynamic_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/219_Lenovo_Dynamic_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/220_Lenovo_Pure_Tone_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/220_Lenovo_Pure_Tone_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/221_Lenovo_Symphony_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/221_Lenovo_Symphony_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/222_Teleport_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/222_Teleport_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/223_GameMoment_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/223_GameMoment_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/223_SecretGarden_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/223_SecretGarden_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/224_Silence_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/224_Silence_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/226_Stars_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/226_Stars_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/227_SunnyDay_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/227_SunnyDay_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/228_Heartbeat_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/228_Heartbeat_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/231_Awoken_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/231_Awoken_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/232_EtherealMallets_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/232_EtherealMallets_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/233_Inception_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/233_Inception_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/234_Lullaby_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/234_Lullaby_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/235_Potpourri_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/235_Potpourri_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/236_Respire_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/236_Respire_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/237_Legion_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/237_Legion_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/239_SecretGarden_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/239_SecretGarden_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/240_Streamer_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/240_Streamer_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/241_Pulse_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/241_Pulse_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/242_Starlight_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/242_Starlight_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/243_Light_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/243_Light_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/245_hihat_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/245_hihat_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/246_kick_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/246_kick_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/247_snare_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/247_snare_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/251_CQA_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/251_CQA_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Ding_RTP_23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Ding_RTP_23.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Ding_RTP_x_23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Ding_RTP_x_23.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Dreams_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Dreams_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Dreams_RTP_x.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Dreams_RTP_x.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/MaLing1_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/MaLing1_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/MaLing1x_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/MaLing1x_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Stars2_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Stars2_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/Stars2x_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/Stars2x_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/TribalLangua_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/TribalLangua_RTP.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/TribalLangua_RTP_x.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/TribalLangua_RTP_x.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/aw8697_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/aw8697_haptic.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/aw8697_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/aw8697_rtp.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/aw8697x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/aw8697x_haptic.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917/aw8697x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917/aw8697x_rtp.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/aw86917_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw86917_haptic.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/chip_init.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/chip_init.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/cy_ccg4_fw_img1.cybin:$(TARGET_COPY_OUT_VENDOR)/firmware/cy_ccg4_fw_img1.cybin \
    vendor/lenovo/halo/proprietary/vendor/firmware/cy_ccg4_fw_img2.cybin:$(TARGET_COPY_OUT_VENDOR)/firmware/cy_ccg4_fw_img2.cybin \
    vendor/lenovo/halo/proprietary/vendor/firmware/dw9781c_halo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dw9781c_halo.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/lenovo/halo/proprietary/vendor/firmware/haptic_ram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_ram.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.halo_ofilm_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.halo_ofilm_ov16a1q.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.halo_qtech_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.halo_qtech_hi1336.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_gc02m1b.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_gc02m1b.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg0.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg0.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg1.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg2.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.sensormodule.sunny_ov50a40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.sunny_ov50a40.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_default.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_qtech_imx766.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_qtech_imx766.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_sunny_imx686.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_sunny_imx686.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_sunny_s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_sunny_s5k3m5.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_sunny_s5kjd1sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_sunny_s5kjd1sp.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.fillmore_truly_s5kjd1sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.fillmore_truly_s5kjd1sp.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.halo_gc02m1b.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.halo_gc02m1b.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.halo_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.halo_hi1336.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.halo_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.halo_ov16a1q.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.halo_ov50a40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.halo_ov50a40.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.qtech_imx766.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.qtech_imx766.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.semco_imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.semco_imx363.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.sunny_imx686.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.sunny_imx686.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.sunny_s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.sunny_s5k3m5.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.sunny_s5kjd1sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.sunny_s5kjd1sp.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.truly_imx563.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.truly_imx563.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/com.qti.tuned.truly_s5kjd1sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.truly_s5kjd1sp.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/lenovo/halo/proprietary/vendor/lib64/camera/imx588.pb:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/imx588.pb

PRODUCT_PACKAGES += \
    c2.dolby.avc.dec \
    c2.dolby.avc.sec.dec \
    c2.dolby.client \
    c2.dolby.egl \
    c2.dolby.hevc.dec \
    c2.dolby.hevc.sec.dec \
    c2.dolby.store \
    libdolbyottcameracontrol \
    libdolbyvision \
    vendor.dolby.hardware.dms@2.0 \
    android.hardware.secure_element@1.0-impl \
    camera.device@1.0-impl \
    com.lenovo.eeprom.halo_hi1336_eeprom \
    com.lenovo.eeprom.halo_ov16a1q_eeprom \
    com.lenovo.eeprom.ov50a40_eeprom \
    com.qti.ois.dw9781c_halo \
    com.qti.sensor.halo_gc02m1b \
    com.qti.sensor.halo_hi1336 \
    com.qti.sensor.halo_ov16a1q \
    com.qti.sensor.halo_ov50a40 \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.realtimebokeh \
    com.arcsoft.node.supernightraw \
    com.bots.node.vendortagwrite \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.lenovo \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper_secure \
    camx.device@3.2-impl \
    camx.device@3.3-impl \
    camx.device@3.4-ext-impl \
    camx.device@3.4-impl \
    camx.device@3.5-ext-impl \
    camx.device@3.5-impl \
    camx.device@3.6-ext-impl \
    camx.device@3.6-impl \
    camx.device@3.7-impl \
    camx.provider@2.4-external \
    camx.provider@2.4-impl \
    camx.provider@2.4-legacy \
    camx.provider@2.5-external \
    camx.provider@2.5-legacy \
    camx.provider@2.6-legacy \
    camx.provider@2.7-legacy \
    com.fingerprints.extension@1.0 \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.arcrawpro \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.gs.sm8450 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr.netrani \
    com.qti.feature2.mfsr.sm8450 \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.fillmore \
    com.qti.settings.sm8450 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    deviceInfoServiceModuleNr \
    android.hardware.gnss-aidl-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    camera.qcom \
    com.qti.chi.override \
    fingerprint.default \
    jcos_nq_client \
    libBSTDSLR \
    libBSTPurpleFringeRemove \
    libDummyPreviewVideoAlgorithm \
    libDummySnapshotAlgorithm \
    libMNN \
    libNvEffectSdkCore_arm64-v8a \
    libQnnGpu \
    libQnnHtp \
    libQnnHtpAltPrepV69Stub \
    libQnnHtpPrepare \
    libQnnHtpStub \
    libQnnHtpV69Stub \
    libQtiRilLoadable \
    libadm \
    libaidenoiser \
    libaidenoiserv2 \
    libarcsoft_chi_utils \
    libarcsoft_dualcam_refocus \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range_v5 \
    libarcsoft_low_light_hdr \
    libarcsoft_qnnhtp \
    libarcsoft_super_night_raw \
    libarcsoft_superportrait \
    libaudio_log_utils \
    libaw_portrait_mask \
    libbatching \
    libc++_shared \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcodec2_soft_ac4dec \
    libcodec2_soft_ddpdec \
    libcodec2_store_dolby \
    libcom.qti.chinodeutils \
    libdapparamstorage \
    libdataitems \
    libdeccfg \
    libdlbdsservice \
    libdlbpreg \
    libgarden \
    libgarden_haltests_e2e \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libhdrdynamic \
    libhdrdynamicootf \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libizat_client_api \
    libizat_core \
    libjni_aidenoiserutilv2 \
    libjpege \
    liblbs_core \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_eng_hub \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblqe \
    libmcs \
    libmctfengine_stub \
    libmfGhostDetection \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_HDSR \
    libmorpho_HdrChecker \
    libmorpho_ImageRefiner \
    libmorpho_Ldc \
    libmorpho_MotionSensor \
    libmorpho_SingleCamBokeh \
    libmpbase \
    libopencv \
    libopencv3a \
    libopestriping \
    libos \
    libpandora.algorithm.360ai.PortraitMask.1 \
    libpandora.algorithm.arcsoft.hdrchecker.1 \
    libpandora.algorithm.arcsoft.lowlighthdr.1 \
    libpandora.algorithm.arcsoft.normalhdr.1 \
    libpandora.algorithm.arcsoft.superPortrait.1 \
    libpandora.algorithm.bst.aicapture.1 \
    libpandora.algorithm.bst.purplefringeremove.1 \
    libpandora.algorithm.lenovo.PictureInPicture.1 \
    libpandora.algorithm.lenovo.Watermark.1 \
    libpandora.algorithm.lenovo.bokeh.1 \
    libpandora.algorithm.meishe.effect.1 \
    libpandora.algorithm.morpho.dc.1 \
    libpandora.algorithm.morpho.dccapture.1 \
    libpandora.algorithm.morpho.denoise.1 \
    libpandora.algorithm.morpho.hdrdetector.1 \
    libpandora.algorithm.morpho.imageRefiner.1 \
    libpandora.algorithm.morpho.motionsensor.1 \
    libpandora.algorithm.morpho.singlebokeh.1 \
    libpandora.algorithm.morpho.sr.1 \
    libpandora.algorithm.niklas.DummyPreviewVideoAlgorithm.1 \
    libpandora.algorithm.niklas.DummySnapshotAlgorithm.1 \
    libpandora.pal.platform.generic.products \
    libpandora.render \
    libpandora \
    libqcrilDataModule \
    libqcrilNr \
    libqcrilNrCellInfoModule \
    libqcrilNrImsModule \
    libqcrilNrPbmModule \
    libqcrilNrQtiBus \
    libqcrilNrSmsModule \
    libqcrilNrSocketModule \
    libqcrilNrVoiceModule \
    libqfp-service \
    libqll \
    libqll10 \
    libqllengine \
    libqmiextservices \
    libqshcamera \
    libqtigefar \
    libril-db \
    libril-legacy \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    librilqmimiscservices \
    libsfeShiftExtrapolation \
    libslimclient \
    libsn100u_fw \
    libsn220u_fw \
    libswregistrationalgo \
    libsynergy_loc_api \
    libsynx \
    libtensorflowlite \
    libtfestriping \
    libthreadutils \
    libubifocus \
    libxtadapter \
    ls_nq_client \
    nfc_nci.nqx.default.hw \
    qcrilInterfaces \
    qcrilMarshal \
    qcrilNr_aidl_IQtiRadioConfig \
    qcril_client \
    qcrild_libqcrilnr \
    qcrild_libqcrilnrutils \
    qtiPeripheralMgr \
    qtiwakelock \
    se_nq_extn_client \
    libasphere \
    libdlbvol \
    libswdap \
    libswgamedap \
    vendor.dolby.dvs@1.0 \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.lenovo.hardware.ifaa@1.0 \
    vendor.nxp.hardware.nfc@2.0 \
    vendor.qti.gnss-V1-ndk_platform \
    vendor.qti.gnss-service \
    vendor.qti.hardware.camera.aon@1.0-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.iwlan@1.1 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.radio.ims-V7-ndk_platform \
    vendor.qti.hardware.radio.qtiradio-V8-ndk_platform \
    vendor.qti.hardware.radio.qtiradioconfig-V2-ndk_platform \
    bm2n00 \
    bm2n01 \
    bm2n02 \
    bm2n03 \
    bm2n04 \
    bm2n05 \
    bm2n06 \
    bm2n07 \
    bm2n08 \
    bm2n09 \
    bm2n10 \
    bm2n11 \
    bm2n12 \
    bm2n13 \
    bm2n14 \
    bm2n15 \
    bm2n16 \
    bm2n17 \
    bm2n18 \
    bm2n19 \
    bm2n20 \
    bm2n21 \
    bm2n22 \
    bm2n23 \
    bm2n24 \
    bm2n25 \
    bm2n26 \
    bm2n27 \
    bm2n31 \
    bm2n32 \
    bm2n33 \
    bm2n34 \
    bm2n35 \
    bm2n36 \
    bm2n37 \
    bm2n38 \
    bm2n39 \
    bm2n40 \
    bm2n41 \
    bm2n42 \
    bm2n43 \
    bm2n44 \
    bm2n45 \
    bm2n46 \
    bm2n47 \
    bm2n48 \
    bm2n49 \
    bm2n50 \
    bm2n51 \
    bm2n52 \
    bm2n53 \
    bm2n54 \
    bm2n55 \
    libDspIOProxy_skel \
    libQ6MSFR_manager_skel \
    libQnnHtpAltPrepV69Skel \
    libQnnHtpV69Skel \
    libVppFrcQnnHtp \
    libVppQnnHtp \
    libadsp_jpege_skel \
    libapn_dsp_skel \
    libbitml_nsp_skel \
    libbitml_nsp_v2_skel \
    libcamera_nn_skel \
    libcvpdsp_2_1 \
    libdspCV_skel \
    libdsp_streamer_binning \
    libdsp_streamer_qvrcam_receiver \
    libevadsp_3_0 \
    libeye_tracking_dsp_sample_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhalide_hexagon_remote_skel \
    libhdr_skel \
    libmctfengine_skel \
    libmobilenet_dsp_frc \
    libmobilenet_dsp_frc_networks \
    libneat_1_1_skel \
    libqvr_cam_dsp_driver_skel \
    libqvr_dsp_driver_skel \
    libscveT2T_skel \
    libtracker_6dof_skel_8250 \
    libtracker_6dof_skel_8350 \
    libvpp_ais_networks \
    libvpp_vqa_networks \
    libvpt_action_recognition \
    IfaaService \
    uimgbaservice \
    QtiTelephony \
    QtiTelephonyService \
    ims \
    qcrilmsgtunnel \
    com.fingerprints.extension \
    uimgbalibrary \
    uimgbamanagerlibrary \
    uimservicelibrary \
    qcrilhook \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.gnss-aidl-service-qti.xml \
    android.hardware.gnss@2.1-service-qti.xml \
    dataconnection-saidl.xml \
    qtiradio-saidl.xml \
    vendor.dolby.hardware.dms.xml \
    vendor.dolby.media.dvs-service.xml \
    vendor.qti.gnss-service.xml \
    vendor.qti.hardware.radio.ims.xml \
    vendor.qti.hardware.radio.qtiradioconfig.xml \
    ATFWD-daemon \
    ccid_daemon_nr \
    garden_app \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.gnss-aidl-service-qti \
    dolbycodec2 \
    dvs-hal-service \
    qcrilNrd \
    qfp-daemon \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.dolby.media.c2@1.0-service \
    vendor.lenovo.hardware.ifaa@1.0-service \
    vendor.nxp.hardware.nfc@2.0-service \
    vendor.qti.camera.provider@2.7-service_64 \
    vendor.qti.secure_element@1.2-service \
    loc_launcher \
    lowi-server \
    mlid \
    qtigetprop \
    qtisetprop \
    slim_daemon \
    thermal-engine-v2 \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent
